//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donate
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DonateEntities1 : DbContext
    {
        public DonateEntities1()
            : base("name=DonateEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnonymousDonate> AnonymousDonate { get; set; }
        public virtual DbSet<ATMInfo> ATMInfo { get; set; }
        public virtual DbSet<BarCodeInfo> BarCodeInfo { get; set; }
        public virtual DbSet<CardInfo> CardInfo { get; set; }
        public virtual DbSet<ChainStoreInfo> ChainStoreInfo { get; set; }
        public virtual DbSet<mytable> mytable { get; set; }
        public virtual DbSet<NamedDonate> NamedDonate { get; set; }
        public virtual DbSet<SiteInfo> SiteInfo { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<WebATMInfo> WebATMInfo { get; set; }
    }
}
