//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donate
{
    using System;
    using System.Collections.Generic;
    
    public partial class NamedDonate
    {
        public System.Guid DonateID { get; set; }
        public string ContributionWay { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Sponsor { get; set; }
        public string DonorName { get; set; }
        public string DonorID { get; set; }
        public string PhoneNumber { get; set; }
        public string Email1 { get; set; }
        public string Email3 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public Nullable<bool> Receipt { get; set; }
        public Nullable<System.DateTime> DonateTime { get; set; }
        public Nullable<System.DateTime> ServerReceiveTime { get; set; }
    }
}
