//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donate
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteInfo
    {
        public int SiteTermID { get; set; }
        public string Candidate { get; set; }
        public bool DefaultSelect { get; set; }
        public string SiteTerm1 { get; set; }
        public string SiteTerm2 { get; set; }
        public string SiteTerm3 { get; set; }
        public string SiteTerm4 { get; set; }
        public string SiteTerm5 { get; set; }
        public string PictureLocation { get; set; }
    }
}
